### ISSUE TITLE
Everything crash after 1 minute

### ISSUE THREAD

**Issue by AnAkIn1** [eliasp/plasma-workspace-units#15]
I just tested with the latest git version, everything seem to work fine, but every time after 1 min all processes seem to be killed, and I get a black screen, I can switch to a VT, and after 30s the VT becomes black as well.

I'm on ArchLinux, had to modify the outdated PKGBUILD in AUR according to the INSTALL instructions.

juil. 23 01:46:37 laptop systemd[1237]: Starting KDE Global Hotkey Manager...
juil. 23 01:46:37 laptop systemd[1237]: Starting KDE 'kdeinit' - TODO...
juil. 23 01:46:37 laptop systemd[1237]: Starting KDE Plasma Workspace Activity Manager...
juil. 23 01:46:37 laptop systemd[1237]: Starting KDE Plasma Workspace Application Launcher...
juil. 23 01:46:37 laptop systemd[1237]: Starting KDE Session Management Server...
juil. 23 01:46:37 laptop systemd[1237]: Starting KDE Service Manager...
juil. 23 01:46:37 laptop systemd[1237]: Starting Baloo file indexer...
juil. 23 01:46:37 laptop systemd[1237]: Starting KDE Secret Wallet...
juil. 23 01:46:37 laptop systemd[1237]: Starting KDE Plasma Workspace Transaction Monitor...
juil. 23 01:46:37 laptop systemd[1237]: Started KDE 'kdeinit' - TODO.
juil. 23 01:46:37 laptop systemd[1237]: Started Baloo file indexer.
juil. 23 01:46:37 laptop systemd[1237]: Started KDE Global Hotkey Manager.
juil. 23 01:47:05 laptop systemd[1237]: Time has been changed
juil. 23 01:48:08 laptop systemd[1237]: kded.service: Start operation timed out. Terminating.
juil. 23 01:48:08 laptop systemd[1237]: kactivitymanagerd.service: Start operation timed out. Terminating.
juil. 23 01:48:08 laptop systemd[1237]: Failed to start KDE Plasma Workspace Activity Manager.
juil. 23 01:48:08 laptop systemd[1237]: Dependency failed for KDE Plasma Workspace.
juil. 23 01:48:08 laptop systemd[1237]: Dependency failed for KDE Plasma Workspace.
juil. 23 01:48:08 laptop systemd[1237]: plasma-workspace.target: Job plasma-workspace.target/start failed with result 'dependency'.
juil. 23 01:48:08 laptop systemd[1237]: plasmashell.service: Job plasmashell.service/start failed with result 'dependency'.
juil. 23 01:48:08 laptop systemd[1237]: kactivitymanagerd.service: Unit entered failed state.
juil. 23 01:48:08 laptop systemd[1237]: kactivitymanagerd.service: Failed with result 'timeout'.
juil. 23 01:48:08 laptop systemd[1237]: kwalletd.service: Start operation timed out. Terminating.
juil. 23 01:48:08 laptop systemd[1237]: kuiserver.service: Start operation timed out. Terminating.
juil. 23 01:48:08 laptop systemd[1237]: krunner.service: Start operation timed out. Terminating.
juil. 23 01:48:08 laptop systemd[1237]: Failed to start KDE Plasma Workspace Application Launcher.
juil. 23 01:48:08 laptop systemd[1237]: krunner.service: Unit entered failed state.
juil. 23 01:48:08 laptop systemd[1237]: krunner.service: Failed with result 'timeout'.
juil. 23 01:48:08 laptop systemd[1237]: Failed to start KDE Secret Wallet.
juil. 23 01:48:08 laptop systemd[1237]: kwalletd.service: Unit entered failed state.
juil. 23 01:48:08 laptop systemd[1237]: kwalletd.service: Failed with result 'timeout'.
juil. 23 01:48:08 laptop systemd[1237]: Failed to start KDE Plasma Workspace Transaction Monitor.
juil. 23 01:48:08 laptop systemd[1237]: kuiserver.service: Unit entered failed state.
juil. 23 01:48:08 laptop systemd[1237]: kuiserver.service: Failed with result 'timeout'.
juil. 23 01:48:08 laptop systemd[1237]: ksmserver.service: Start operation timed out. Terminating.
juil. 23 01:48:08 laptop systemd[1237]: Starting KDE Window Manager...
juil. 23 01:48:08 laptop systemd[1237]: Failed to start KDE Session Management Server.
juil. 23 01:48:08 laptop systemd[1237]: ksmserver.service: Unit entered failed state.
juil. 23 01:48:08 laptop systemd[1237]: ksmserver.service: Failed with result 'timeout'.
juil. 23 01:48:08 laptop systemd[1237]: Failed to start KDE Service Manager.
juil. 23 01:48:08 laptop systemd[1237]: Dependency failed for KDE Window Manager.
juil. 23 01:48:08 laptop systemd[1237]: kwin.service: Job kwin.service/start failed with result 'dependency'.
juil. 23 01:48:08 laptop systemd[1237]: kded.service: Unit entered failed state.
juil. 23 01:48:08 laptop systemd[1237]: kded.service: Failed with result 'timeout'.
juil. 23 01:48:33 laptop systemd[1237]: kwin.service: Main process exited, code=exited, status=1/FAILURE
juil. 23 01:48:33 laptop systemd[1237]: kwin.service: Unit entered failed state.
juil. 23 01:48:33 laptop systemd[1237]: kwin.service: Failed with result 'exit-code'.

**Comment by bhush9** [comment]
Latest update won't work with the archlinux, please revert to older version. It requires systemd-git with https://github.com/systemd/systemd/pull/606 applied. I am updating my PKGBUILD to use older revision till this PR is released.

**Comment by bhush9** [comment]
updated AUR PKGBUILD to use 8729d6dcbfebfedb3b365fa01ec431ea01b17a9c revision, will update PKGBUILD to use latest git master as soon as it starts working properly.

**Comment by AnAkIn1** [comment]
Thanks, it now works fine :) Does that mean that kdbus will now be required with future versions?

**Comment by bhush9** [comment]
Yes, kdbus is hard dependency for plasma-workspace-units since last commits.

**Comment by AnAkIn1** [comment]
Ok, I guess this can be closed.

**Comment by AnAkIn1** [comment]
systemd 223 is now in core, I think you can stop using that specific commit in the PKGBUILD.

**Comment by bhush9** [comment]
@AnAkIn1 if you have modified PKGBUILD feel free to use it, currently I am holding out to specific revision because things are not usable with kdbus currently and kdbus is not enabled in systemd package https://projects.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/systemd#n54

**Comment by AnAkIn1** [comment]
@bhush9 kdbus doesn't need to be enabled in the systemd package. Simply adding "kdbus" to the kernel parameters work, --disable-kdbus just change whether it's enabled by default or not.

**Comment by bhush9** [comment]
Alright, then I must have misunderstood.. Give me some time, I will update PKGBUILD in approx hour.

**Comment by bhush9** [comment]
@AnAkIn1 : On second thought it would be good idea to wait till we at least issue #19 is resolved and SystemdService=<foobar> is added in files provided by plasma-workspace/desktop, otherwise files will conflict and cause issues, with normal session.

We have just filled sysadmin request to create repository for this units. So once this is moved to KDE infrastructure we can add them.

I am fine with either.. what do you think?

**Comment by AnAkIn1** [comment]
Right, I guess it has to wait for inclusion in official packages, otherwise it will always conflict.
