### ISSUE TITLE
startsystemd generating errors in .xsession-errors

### ISSUE THREAD

**Issue by AnAkIn1** [eliasp/plasma-workspace-units#17]
There are a few errors in .xsession-errors which are related to startsystemd:

1) rm ${LOGFILE} causes an error because the logfile doesn't exist, should probably add the -f flag to ignore non-existent files
2) SESSION_ENV_FILE is not defined, both rm and touch will also cause an error

**Comment by eliasp** [comment]
You're right… I knew of them but kept ignoring them :)
Will fix this ASAP.

**Comment by bhush9** [comment]
This can be closed now..
