### ISSUE TITLE
krunner always show up after login

### ISSUE THREAD

**Issue by AnAkIn1** [eliasp/plasma-workspace-units#18]
While using the systemd session, the krunner bar always show up on login and I need to close it every time. It doesn't show up with the regular plasma session.

**Comment by eliasp** [comment]
@bhush9 IIRC you tracked this down at some point in the past. It was something like "krunner is also launched by plasmashell".
Do you remember more details?

If it's plasmashell launching it and it uses DBus activation to start it, this issue will be gone with kdbus as it prevents these kind of race conditions.

**Comment by bhush9** [comment]
@eliasp right, this can be closed

@AnAkIn1 to work around : Remove /etc/xdg/autostart/krunner.desktop

**Comment by eliasp** [comment]
@bhush9 Thanks a lot!

**Comment by AnAkIn1** [comment]
I am now using kdbus and it still shows up. Is this normal?
The workaround works though.

**Comment by eliasp** [comment]
Please check:

- whether you have overwritten your existing `/usr/share/dbus-1/services/org.kde.krunner.service` with the one from the repo (it needs to contain `SystemdService=krunner.service`)
- whether `systemctl --user status org.kde.krunner.busname` is `active (listening)`
- whether one of your running krunner instances doesn't belong to the service `krunner`: `systemctl --user status $(pidof krunner)`

**Comment by AnAkIn1** [comment]
1) Yes
2) Yes
3) This does return the systemd service status
systemd[1416]: Starting KDE Plasma Workspace Application Launcher...
systemd[1416]: Started KDE Plasma Workspace Application Launcher.
krunner[1467]: default unknown: Trying to use rootObject before initialization is completed, whilst using setInitializationDelayed. Forcing completion
